[theme]
primaryColor = "#00D09C"
backgroundColor = "#F6F7F9"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#171a2c"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
